GET http://localhost:3000/api/anime/get-providers
###
GET http://localhost:3000/api/anime/recents
provider: jkanime

###

GET http://localhost:3000/api/anime/episode?url=/ver/shaman-king-2021-20
provider: tioanime

###

GET  http://localhost:3000/api/anime/new-season


###

GET  https://api.jikan.moe/v3/season/later

###
POST http://localhost:3000/api/anime/anime-trad HTTP/1.1
content-type: application/json

{
    "to": "es",
    "txt": "Directly after the events of Made in Abyss Movie 3: Dawn of the Deep Soul, the third installment of Made in Abyss covers the adventure of Reg, Riko, and Nanachi in the Sixth Layer, The Capital of the Unreturned."
}

