GET http://localhost:3000/api/anime/get-providers
###
GET http://localhost:3000/api/anime/recents
provider: tioanime

###

GET http://localhost:3000/api/anime/episode?url=/ver/shaman-king-2021-20
provider: tioanime

