GET http://localhost:3000/api/anime/get-providers
###
GET http://localhost:3000/api/anime/recents
provider: jkanime

###

GET http://localhost:3000/api/anime/episode?url=/ver/shaman-king-2021-20
provider: tioanime

###

GET  http://localhost:3000/api/anime/new-season


###

GET  https://api.jikan.moe/v3/season/later


###

POST  https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&from=en&to=es HTTP/1.1
Ocp-Apim-Subscription-Key: c3f68e236d2047b69d65b187e386c093
Ocp-Apim-Subscription-Region: centralus
Content-type: application/json
Content-length: 2000

[{'Text':"Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.\r\n\r\nUnfortunately, he has outlived his usefulness and is murdered by a devil in contract with the yakuza. However, in an unexpected turn of events, Pochita merges with Denji's dead body and grants him the powers of a chainsaw devil. Now able to transform parts of his body into chainsaws, a revived Denji uses his new abilities to quickly and brutally dispatch his enemies. Catching the eye of the official devil hunters who arrive at the scene, he is offered work at the Public Safety Bureau as one of them. Now with the means to face even the toughest of enemies, Denji will stop at nothing to achieve his simple teenage dreams.\r\n\r\n[Written by MAL Rewrite]"}]


###
POST http://localhost:3000/api/anime/anime-trad HTTP/1.1
content-type: application/json

